manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/mike1808
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: mm/experiments
      import: app/west.yml
  self:
    path: config
